# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage_location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('last_reorder_date', models.DateTimeField(blank=True, null=True, verbose_name='last reorder date')),
                ('last_reorder_quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HighVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage_location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('last_reorder_date', models.DateTimeField(blank=True, null=True, verbose_name='last reorder date')),
                ('last_reorder_quantity', models.IntegerField(default=0)),
                ('consumable_location', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('storage_location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('last_reorder_date', models.DateTimeField(blank=True, null=True, verbose_name='last reorder date')),
                ('last_reorder_quantity', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
